# Generated by Django 2.1.5 on 2020-03-10 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 13, 1, 34, 164330, tzinfo=utc)),
        ),
    ]
